// installer.cpp — look install <github.com/user/repo[@ref]>
// Downloads ZIP from GitHub, extracts to pkg/user/repo/, updates look.lock.
// Zero dependencies: uses existing http_client (Schannel/OpenSSL) + miniz.
#include "look/installer.h"
#include "look/http_client.h"
#include "miniz/miniz.h"

#include <iostream>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <string>
#include <map>
#include <vector>
#include <algorithm>
#include <stdexcept>

namespace fs = std::filesystem;

namespace look {

// ── look.lock helpers ─────────────────────────────────────────────────────────

struct LockEntry {
    std::string ref;    // "main", "v1.2", commit sha
    std::string sha;    // resolved commit sha (or "" if unknown)
};

// Read look.lock → map{"user/repo" → LockEntry}
static std::map<std::string, LockEntry> read_lock(const fs::path& lock_path) {
    std::map<std::string, LockEntry> result;
    if (!fs::exists(lock_path)) return result;

    std::ifstream f(lock_path);
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        // format: "user/repo" = "ref@sha"  or  "user/repo" = "ref"
        auto eq = line.find('=');
        if (eq == std::string::npos) continue;
        std::string key = line.substr(0, eq);
        std::string val = line.substr(eq + 1);
        // strip whitespace and quotes
        auto strip = [](std::string& s) {
            while (!s.empty() && (s.front() == ' ' || s.front() == '"')) s.erase(s.begin());
            while (!s.empty() && (s.back()  == ' ' || s.back()  == '"')) s.pop_back();
        };
        strip(key); strip(val);

        LockEntry e;
        auto at = val.find('@');
        if (at != std::string::npos) {
            e.ref = val.substr(0, at);
            e.sha = val.substr(at + 1);
        } else {
            e.ref = val;
        }
        result[key] = e;
    }
    return result;
}

// Write look.lock from map (sorted, deterministic)
static void write_lock(const fs::path& lock_path,
                        const std::map<std::string, LockEntry>& entries)
{
    std::ofstream f(lock_path);
    f << "# look.lock — generated by look install, do not edit manually\n";
    for (auto& [key, e] : entries) {
        f << '"' << key << '"' << " = \"" << e.ref;
        if (!e.sha.empty()) f << '@' << e.sha;
        f << "\"\n";
    }
}

// ── Package name parsing ──────────────────────────────────────────────────────

struct PkgSpec {
    std::string host;    // "github.com"
    std::string user;
    std::string repo;
    std::string subdir;  // optional: "firebase" from look-packages/firebase
    std::string ref;     // branch/tag, default "main"

    // look.lock key: "user/repo" or "user/repo/subdir"
    std::string lock_key() const {
        return subdir.empty() ? (user + "/" + repo)
                              : (user + "/" + repo + "/" + subdir);
    }
    // local install dir: "pkg/firebase" (subdir name) or "pkg/user/repo"
    std::string pkg_dir() const {
        return subdir.empty() ? ("pkg/" + user + "/" + repo)
                              : ("pkg/" + subdir);
    }
    std::string zip_url() const {
        return "https://api.github.com/repos/" + user + "/" + repo + "/zipball/" + ref;
    }
};

static PkgSpec parse_pkg(const std::string& input) {
    PkgSpec p;
    std::string s = input;

    // strip leading https:// or http://
    if (s.substr(0, 8) == "https://") s = s.substr(8);
    else if (s.substr(0, 7) == "http://") s = s.substr(7);

    // optional @ref suffix
    auto at = s.rfind('@');
    if (at != std::string::npos) {
        p.ref = s.substr(at + 1);
        s     = s.substr(0, at);
    } else {
        p.ref = "main";
    }

    // host
    auto s1 = s.find('/');
    if (s1 == std::string::npos) throw std::runtime_error("Geçersiz paket: " + input);
    p.host = s.substr(0, s1);
    s      = s.substr(s1 + 1);

    // user
    auto s2 = s.find('/');
    if (s2 == std::string::npos) throw std::runtime_error("Geçersiz paket (user/repo gerekli): " + input);
    p.user = s.substr(0, s2);
    s      = s.substr(s2 + 1);

    // repo[/subdir]
    auto s3 = s.find('/');
    if (s3 == std::string::npos) {
        p.repo = s;  // whole repo, no subdir
    } else {
        p.repo   = s.substr(0, s3);
        p.subdir = s.substr(s3 + 1);
        // strip trailing slash if any
        if (!p.subdir.empty() && p.subdir.back() == '/')
            p.subdir.pop_back();
    }

    if (p.host != "github.com")
        throw std::runtime_error("Şu an sadece github.com destekleniyor.");

    return p;
}

// ── ZIP extraction ────────────────────────────────────────────────────────────

// GitHub zipball: "{repo}-{sha}/" prefix + optional subdir filter
// subdir_filter: if non-empty, only extract files under that subdirectory
static bool extract_zip(const std::vector<char>& data,
                         const fs::path& dest_dir,
                         bool verbose,
                         const std::string& subdir_filter = "")
{
    mz_zip_archive zip{};
    if (!mz_zip_reader_init_mem(&zip, data.data(), data.size(), 0)) {
        std::cerr << "ZIP açma hatası: " << mz_zip_get_error_string(mz_zip_get_last_error(&zip)) << "\n";
        return false;
    }

    int n = (int)mz_zip_reader_get_num_files(&zip);
    if (n == 0) { mz_zip_reader_end(&zip); return false; }

    // GitHub prepends "repo-sha/" to all paths — detect and strip that prefix
    std::string strip_prefix;
    {
        mz_zip_archive_file_stat st;
        if (mz_zip_reader_file_stat(&zip, 0, &st)) {
            std::string first = st.m_filename;
            auto slash = first.find('/');
            if (slash != std::string::npos) strip_prefix = first.substr(0, slash + 1);
        }
    }

    // subdir filter prefix: after stripping GitHub prefix, files must start with "subdir/"
    std::string subdir_prefix = subdir_filter.empty() ? "" : (subdir_filter + "/");

    fs::create_directories(dest_dir);
    int extracted = 0;

    for (int i = 0; i < n; ++i) {
        mz_zip_archive_file_stat st;
        if (!mz_zip_reader_file_stat(&zip, i, &st)) continue;

        std::string filename = st.m_filename;

        // Strip GitHub prefix
        if (!strip_prefix.empty() && filename.substr(0, strip_prefix.size()) == strip_prefix)
            filename = filename.substr(strip_prefix.size());
        if (filename.empty()) continue;

        // Subdir filter: skip files not under the requested subdirectory
        if (!subdir_prefix.empty()) {
            if (filename.substr(0, subdir_prefix.size()) != subdir_prefix) continue;
            // Strip subdir prefix so files land directly in dest_dir
            filename = filename.substr(subdir_prefix.size());
            if (filename.empty()) continue;
        }

        // Zip Slip koruması: normalize edilmiş yolun dest_dir içinde kalması zorunlu
        fs::path safe_dest = fs::weakly_canonical(dest_dir);
        fs::path out_path  = fs::weakly_canonical(dest_dir / filename);
        auto dest_str = safe_dest.string();
        auto out_str  = out_path.string();
        if (out_str.size() < dest_str.size() ||
            out_str.compare(0, dest_str.size(), dest_str) != 0) {
            if (verbose) std::cerr << "  ATLANDI (güvenlik): " << filename << "\n";
            continue;
        }

        if (mz_zip_reader_is_file_a_directory(&zip, i)) {
            fs::create_directories(out_path);
            continue;
        }

        fs::create_directories(out_path.parent_path());

        size_t out_size = 0;
        void* buf = mz_zip_reader_extract_to_heap(&zip, i, &out_size, 0);
        if (!buf) {
            if (verbose) std::cerr << "  Çıkartılamadı: " << filename << "\n";
            continue;
        }

        std::ofstream ofs(out_path, std::ios::binary);
        if (ofs) ofs.write((char*)buf, (std::streamsize)out_size);
        mz_free(buf);
        ++extracted;

        if (verbose) std::cout << "  + " << filename << "\n";
    }

    mz_zip_reader_end(&zip);

    if (extracted == 0 && !subdir_filter.empty()) {
        std::cerr << "Hata: '" << subdir_filter << "' klasörü repoda bulunamadı.\n";
        return false;
    }
    return true;
}

// ── Download with redirect follow ─────────────────────────────────────────────

static HttpResponse download_follow(const std::string& url, bool verbose, int max_redirects = 5) {
    std::string current = url;
    HttpOptions opts;
    opts.timeout_ms = 30000;  // 30s for large ZIPs

    for (int i = 0; i < max_redirects; ++i) {
        if (verbose) std::cout << "  İndiriliyor: " << current << "\n";

        std::map<std::string, std::string> headers;
        headers["Accept"]     = "application/zip";
        headers["User-Agent"] = "LOOK-Package-Manager/0.25";

        HttpResponse resp = http_request("GET", current, "", headers, opts);

        if (!resp.error.empty()) return resp;

        // 3xx redirect
        if (resp.status >= 300 && resp.status < 400) {
            auto it = resp.headers.find("location");
            if (it == resp.headers.end()) {
                resp.error = "redirect konum başlığı yok";
                return resp;
            }
            current = it->second;
            continue;
        }
        return resp;
    }

    HttpResponse r;
    r.error = "çok fazla yönlendirme";
    return r;
}

// ── Resolve commit SHA via GitHub API ─────────────────────────────────────────

static std::string resolve_sha(const PkgSpec& spec, bool verbose) {
    // GET https://api.github.com/repos/{user}/{repo}/commits/{ref}
    std::string url = "https://api.github.com/repos/" + spec.user + "/" + spec.repo
                    + "/commits/" + spec.ref;
    if (verbose) std::cout << "  SHA çözümleniyor...\n";

    std::map<std::string, std::string> hdrs;
    hdrs["Accept"]     = "application/vnd.github.sha";
    hdrs["User-Agent"] = "LOOK-Package-Manager/0.25";

    HttpOptions opts;
    opts.timeout_ms = 10000;
    HttpResponse resp = http_request("GET", url, "", hdrs, opts);
    if (!resp.error.empty() || resp.status != 200) return "";

    // Response body is just the 40-char SHA when Accept: application/vnd.github.sha
    std::string sha = resp.body;
    // trim whitespace
    while (!sha.empty() && (sha.back() == '\n' || sha.back() == '\r' || sha.back() == ' '))
        sha.pop_back();
    if (sha.size() == 40) return sha;
    return "";
}

// ── cmd_install ───────────────────────────────────────────────────────────────

int cmd_install(const std::string& pkg, bool verbose) {
    PkgSpec spec;
    try {
        spec = parse_pkg(pkg);
    } catch (const std::exception& e) {
        std::cerr << "Hata: " << e.what() << "\n";
        return 1;
    }

    std::cout << "Yükleniyor: " << spec.user << "/" << spec.repo;
    if (!spec.subdir.empty()) std::cout << "/" << spec.subdir;
    std::cout << " (" << spec.ref << ")\n";

    // Download ZIP
    HttpResponse resp = download_follow(spec.zip_url(), verbose);
    if (!resp.error.empty()) {
        std::cerr << "İndirme hatası: " << resp.error << "\n";
        return 1;
    }
    if (resp.status != 200) {
        std::cerr << "GitHub " << resp.status << " döndürdü — paket bulunamadı: "
                  << spec.user << "/" << spec.repo << "\n";
        return 1;
    }

    std::cout << "  " << (resp.body.size() / 1024) << " KB indirildi\n";

    // Extract
    fs::path dest = spec.pkg_dir();
    if (fs::exists(dest)) {
        if (verbose) std::cout << "  Önceki kurulum temizleniyor...\n";
        fs::remove_all(dest);
    }

    std::vector<char> zip_data(resp.body.begin(), resp.body.end());
    if (!extract_zip(zip_data, dest, verbose, spec.subdir)) {
        std::cerr << "ZIP çıkartma hatası\n";
        return 1;
    }

    std::cout << "  → " << dest.string() << "\n";

    // Update look.lock
    auto lock_path = fs::current_path() / "look.lock";
    auto lock      = read_lock(lock_path);

    // Try to extract commit SHA from Content-Disposition or URL
    // GitHub sends: attachment; filename=user-repo-{sha}.zip
    std::string sha;
    auto it = resp.headers.find("content-disposition");
    if (it != resp.headers.end()) {
        auto& cd = it->second;
        auto fn_pos = cd.find("filename=");
        if (fn_pos != std::string::npos) {
            std::string fn = cd.substr(fn_pos + 9);
            // strip quotes
            if (!fn.empty() && fn[0] == '"') fn = fn.substr(1);
            auto q = fn.find('"');
            if (q != std::string::npos) fn = fn.substr(0, q);
            // filename = repo-sha.zip → extract sha
            auto dot = fn.rfind(".zip");
            if (dot != std::string::npos) fn = fn.substr(0, dot);
            auto dash = fn.rfind('-');
            if (dash != std::string::npos) {
                sha = fn.substr(dash + 1);
                // GitHub SHAs are 40 hex chars
                if (sha.size() != 40) sha.clear();
            }
        }
    }

    // Try to resolve exact commit SHA if not already extracted from zip filename
    if (sha.empty()) sha = resolve_sha(spec, verbose);

    LockEntry entry;
    entry.ref = spec.ref;
    entry.sha = sha;
    lock[spec.lock_key()] = entry;
    write_lock(lock_path, lock);

    std::cout << "  look.lock güncellendi\n";
    std::cout << "✓ " << spec.lock_key() << " kuruldu\n\n";
    std::cout << "Kullanım:\n";
    if (!spec.subdir.empty()) {
        // pkg/firebase/firebase.lk
        std::cout << "  use \"" << spec.pkg_dir() << "/" << spec.subdir << ".lk\";\n";
    } else {
        std::cout << "  use \"" << spec.pkg_dir() << "/" << spec.repo << ".lk\";\n";
    }

    return 0;
}

// ── cmd_install_all ───────────────────────────────────────────────────────────

int cmd_install_all(bool verbose) {
    auto lock_path = fs::current_path() / "look.lock";
    if (!fs::exists(lock_path)) {
        std::cout << "look.lock bulunamadı — kurulacak paket yok.\n";
        return 0;
    }

    auto lock = read_lock(lock_path);
    if (lock.empty()) {
        std::cout << "look.lock boş — kurulacak paket yok.\n";
        return 0;
    }

    std::cout << lock.size() << " paket yükleniyor...\n";
    int failed = 0;
    for (auto& [key, entry] : lock) {
        std::string pkg_str = "github.com/" + key + "@" + entry.ref;
        if (cmd_install(pkg_str, verbose) != 0) ++failed;
    }

    if (failed > 0) {
        std::cerr << failed << " paket yüklenemedi.\n";
        return 1;
    }
    std::cout << "Tüm paketler yüklendi.\n";
    return 0;
}

// ── Module helpers ────────────────────────────────────────────────────────────

static fs::path look_home() {
#ifdef _WIN32
    const char* home = std::getenv("USERPROFILE");
    if (!home) home = std::getenv("HOMEDRIVE");
#else
    const char* home = std::getenv("HOME");
#endif
    if (!home) throw std::runtime_error("HOME dizini bulunamadı");
    return fs::path(home) / ".look";
}

static fs::path modules_dir() {
    return look_home() / "modules";
}

// ── cmd_module_install ────────────────────────────────────────────────────────

int cmd_module_install(const std::string& pkg_url, bool verbose) {
    PkgSpec spec;
    try {
        spec = parse_pkg(pkg_url);
    } catch (const std::exception& e) {
        std::cerr << "Hata: " << e.what() << "\n";
        std::cerr << "Örnek: lk module install github.com/codlook/look-modules/jwt\n";
        return 1;
    }

    // Module name = subdir if given, otherwise repo name
    std::string mod_name = spec.subdir.empty() ? spec.repo : spec.subdir;

    std::cout << "Modül yükleniyor: " << spec.user << "/" << spec.repo;
    if (!spec.subdir.empty()) std::cout << "/" << spec.subdir;
    std::cout << " (" << spec.ref << ")\n";

    // Download ZIP from GitHub
    HttpResponse resp = download_follow(spec.zip_url(), verbose);
    if (!resp.error.empty()) {
        std::cerr << "İndirme hatası: " << resp.error << "\n";
        return 1;
    }
    if (resp.status != 200) {
        std::cerr << "GitHub " << resp.status << " döndürdü — modül bulunamadı: "
                  << spec.user << "/" << spec.repo << "\n";
        return 1;
    }

    std::cout << "  " << (resp.body.size() / 1024) << " KB indirildi\n";

    // Extract to ~/.look/modules/<mod_name>/
    fs::path dest_dir = modules_dir() / mod_name;
    if (fs::exists(dest_dir)) {
        if (verbose) std::cout << "  Önceki kurulum temizleniyor...\n";
        fs::remove_all(dest_dir);
    }

    std::vector<char> zip_data(resp.body.begin(), resp.body.end());
    if (!extract_zip(zip_data, dest_dir, verbose, spec.subdir)) {
        std::cerr << "ZIP çıkartma hatası\n";
        return 1;
    }

    std::cout << "  → " << dest_dir.string() << "\n";
    std::cout << "✓ " << mod_name << " modülü kuruldu\n\n";
    std::cout << "Kullanım:\n";
    std::cout << "  use " << mod_name << "\n";

    return 0;
}

// ── cmd_module_list ───────────────────────────────────────────────────────────

// Parse GitHub API JSON array of directory entries, extract "name" fields
// Minimal hand-rolled parser — avoids any JSON dep
static std::vector<std::string> parse_github_dir_names(const std::string& json) {
    std::vector<std::string> names;
    // Each entry: {"name":"jwt","type":"dir",...}
    // We find all "name":"<value>" where the surrounding object has "type":"dir"
    size_t pos = 0;
    while (pos < json.size()) {
        // Find next object boundary
        auto obj_start = json.find('{', pos);
        if (obj_start == std::string::npos) break;
        auto obj_end = json.find('}', obj_start);
        if (obj_end == std::string::npos) break;

        std::string obj = json.substr(obj_start, obj_end - obj_start + 1);

        // Only process directory entries
        if (obj.find("\"type\":\"dir\"") != std::string::npos) {
            auto name_pos = obj.find("\"name\":\"");
            if (name_pos != std::string::npos) {
                name_pos += 8;
                auto name_end = obj.find('"', name_pos);
                if (name_end != std::string::npos) {
                    names.push_back(obj.substr(name_pos, name_end - name_pos));
                }
            }
        }
        pos = obj_end + 1;
    }
    return names;
}

int cmd_module_list() {
    // Fetch official module list from codlook/look-modules via GitHub Contents API
    const std::string api_url =
        "https://api.github.com/repos/codlook/look-modules/contents/";

    std::cout << "Resmi modüller getiriliyor...\n";

    HttpOptions opts;
    opts.timeout_ms = 10000;
    std::map<std::string, std::string> hdrs;
    hdrs["Accept"]     = "application/vnd.github.v3+json";
    hdrs["User-Agent"] = "LOOK-Module-Manager/1.0";

    HttpResponse resp = http_request("GET", api_url, "", hdrs, opts);

    if (!resp.error.empty()) {
        std::cerr << "Bağlantı hatası: " << resp.error << "\n";
        return 1;
    }
    if (resp.status != 200) {
        std::cerr << "GitHub API " << resp.status << " döndürdü\n";
        return 1;
    }

    std::vector<std::string> official = parse_github_dir_names(resp.body);

    // Collect locally installed modules
    fs::path mdir = modules_dir();
    std::vector<std::string> installed;
    if (fs::exists(mdir)) {
        for (auto& entry : fs::directory_iterator(mdir)) {
            if (entry.is_directory()) {
                std::string mname = entry.path().filename().string();
                fs::path lk = entry.path() / (mname + ".lk");
                if (fs::exists(lk)) installed.push_back(mname);
            }
        }
    }

    auto is_installed = [&](const std::string& name) {
        return std::find(installed.begin(), installed.end(), name) != installed.end();
    };

    // Print official modules with install status
    if (official.empty()) {
        std::cout << "Resmi modül bulunamadı.\n";
    } else {
        std::cout << "\nResmi modüller (github.com/codlook/look-modules):\n";
        for (auto& name : official) {
            std::string status = is_installed(name) ? " [kurulu]" : "";
            std::cout << "  " << name << status << "\n";
        }
        std::cout << "\nKurulum: lk module install github.com/codlook/look-modules/<isim>\n";
    }

    // Print any extra locally installed (non-official) modules
    std::vector<std::string> extra;
    for (auto& m : installed) {
        if (std::find(official.begin(), official.end(), m) == official.end())
            extra.push_back(m);
    }
    if (!extra.empty()) {
        std::cout << "\nÜçüncü taraf (yüklü):\n";
        for (auto& m : extra) std::cout << "  " << m << "\n";
    }

    if (official.empty() && installed.empty()) {
        std::cout << "Yüklü modül yok.\n";
    }

    std::cout << "\nModül dizini: " << mdir.string() << "\n";
    return 0;
}

} // namespace look
