// installer.cpp — look install <github.com/user/repo[@ref]>
// Downloads ZIP from GitHub, extracts to pkg/user/repo/, updates look.lock.
// Zero dependencies: uses existing http_client (Schannel/OpenSSL) + miniz.
#include "look/installer.h"
#include "look/http_client.h"
#include "miniz/miniz.h"

#include <iostream>
#include <fstream>
#include <sstream>
#include <filesystem>
#include <string>
#include <map>
#include <vector>
#include <algorithm>
#include <stdexcept>

namespace fs = std::filesystem;

namespace look {

// ── look.lock helpers ─────────────────────────────────────────────────────────

struct LockEntry {
    std::string ref;    // "main", "v1.2", commit sha
    std::string sha;    // resolved commit sha (or "" if unknown)
};

// Read look.lock → map{"user/repo" → LockEntry}
static std::map<std::string, LockEntry> read_lock(const fs::path& lock_path) {
    std::map<std::string, LockEntry> result;
    if (!fs::exists(lock_path)) return result;

    std::ifstream f(lock_path);
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        // format: "user/repo" = "ref@sha"  or  "user/repo" = "ref"
        auto eq = line.find('=');
        if (eq == std::string::npos) continue;
        std::string key = line.substr(0, eq);
        std::string val = line.substr(eq + 1);
        // strip whitespace and quotes
        auto strip = [](std::string& s) {
            while (!s.empty() && (s.front() == ' ' || s.front() == '"')) s.erase(s.begin());
            while (!s.empty() && (s.back()  == ' ' || s.back()  == '"')) s.pop_back();
        };
        strip(key); strip(val);

        LockEntry e;
        auto at = val.find('@');
        if (at != std::string::npos) {
            e.ref = val.substr(0, at);
            e.sha = val.substr(at + 1);
        } else {
            e.ref = val;
        }
        result[key] = e;
    }
    return result;
}

// Write look.lock from map (sorted, deterministic)
static void write_lock(const fs::path& lock_path,
                        const std::map<std::string, LockEntry>& entries)
{
    std::ofstream f(lock_path);
    f << "# look.lock — generated by look install, do not edit manually\n";
    for (auto& [key, e] : entries) {
        f << '"' << key << '"' << " = \"" << e.ref;
        if (!e.sha.empty()) f << '@' << e.sha;
        f << "\"\n";
    }
}

// ── Package name parsing ──────────────────────────────────────────────────────

struct PkgSpec {
    std::string host;   // "github.com"
    std::string user;
    std::string repo;
    std::string ref;    // branch/tag, default "main"

    std::string lock_key()  const { return user + "/" + repo; }
    std::string pkg_dir()   const { return "pkg/" + user + "/" + repo; }
    std::string zip_url()   const {
        // GitHub zipball: https://api.github.com/repos/{user}/{repo}/zipball/{ref}
        return "https://api.github.com/repos/" + user + "/" + repo + "/zipball/" + ref;
    }
};

static PkgSpec parse_pkg(const std::string& input) {
    PkgSpec p;
    std::string s = input;

    // strip leading https:// or http://
    if (s.substr(0, 8) == "https://") s = s.substr(8);
    else if (s.substr(0, 7) == "http://") s = s.substr(7);

    // optional @ref suffix
    auto at = s.rfind('@');
    if (at != std::string::npos) {
        p.ref = s.substr(at + 1);
        s     = s.substr(0, at);
    } else {
        p.ref = "main";
    }

    // host/user/repo
    auto s1 = s.find('/');
    if (s1 == std::string::npos) throw std::runtime_error("Geçersiz paket: " + input);
    p.host = s.substr(0, s1);
    s      = s.substr(s1 + 1);

    auto s2 = s.find('/');
    if (s2 == std::string::npos) throw std::runtime_error("Geçersiz paket (user/repo gerekli): " + input);
    p.user = s.substr(0, s2);
    p.repo = s.substr(s2 + 1);

    if (p.host != "github.com")
        throw std::runtime_error("Şu an sadece github.com destekleniyor. Registry (packages.codlook.com) v1.1'de gelecek.");

    return p;
}

// ── ZIP extraction ────────────────────────────────────────────────────────────

// GitHub zipball extracts as "{repo}-{sha}/" — we want pkg/user/repo/
static bool extract_zip(const std::vector<char>& data,
                         const fs::path& dest_dir,
                         bool verbose)
{
    mz_zip_archive zip{};
    if (!mz_zip_reader_init_mem(&zip, data.data(), data.size(), 0)) {
        std::cerr << "ZIP açma hatası: " << mz_zip_get_error_string(mz_zip_get_last_error(&zip)) << "\n";
        return false;
    }

    int n = (int)mz_zip_reader_get_num_files(&zip);
    if (n == 0) { mz_zip_reader_end(&zip); return false; }

    // GitHub prepends "repo-sha/" to all paths — detect and strip that prefix
    std::string strip_prefix;
    {
        mz_zip_archive_file_stat st;
        if (mz_zip_reader_file_stat(&zip, 0, &st)) {
            std::string first = st.m_filename;
            auto slash = first.find('/');
            if (slash != std::string::npos) strip_prefix = first.substr(0, slash + 1);
        }
    }

    fs::create_directories(dest_dir);

    for (int i = 0; i < n; ++i) {
        mz_zip_archive_file_stat st;
        if (!mz_zip_reader_file_stat(&zip, i, &st)) continue;

        std::string filename = st.m_filename;

        // Strip GitHub prefix
        if (!strip_prefix.empty() && filename.substr(0, strip_prefix.size()) == strip_prefix)
            filename = filename.substr(strip_prefix.size());
        if (filename.empty()) continue;

        fs::path out_path = dest_dir / filename;

        if (mz_zip_reader_is_file_a_directory(&zip, i)) {
            fs::create_directories(out_path);
            continue;
        }

        // Ensure parent directory exists
        fs::create_directories(out_path.parent_path());

        // Extract file
        size_t out_size = 0;
        void* buf = mz_zip_reader_extract_to_heap(&zip, i, &out_size, 0);
        if (!buf) {
            if (verbose) std::cerr << "  Çıkartılamadı: " << filename << "\n";
            continue;
        }

        std::ofstream ofs(out_path, std::ios::binary);
        if (ofs) ofs.write((char*)buf, (std::streamsize)out_size);
        mz_free(buf);

        if (verbose) std::cout << "  + " << filename << "\n";
    }

    mz_zip_reader_end(&zip);
    return true;
}

// ── Download with redirect follow ─────────────────────────────────────────────

static HttpResponse download_follow(const std::string& url, bool verbose, int max_redirects = 5) {
    std::string current = url;
    HttpOptions opts;
    opts.timeout_ms = 30000;  // 30s for large ZIPs

    for (int i = 0; i < max_redirects; ++i) {
        if (verbose) std::cout << "  İndiriliyor: " << current << "\n";

        std::map<std::string, std::string> headers;
        headers["Accept"]     = "application/zip";
        headers["User-Agent"] = "LOOK-Package-Manager/0.25";

        HttpResponse resp = http_request("GET", current, "", headers, opts);

        if (!resp.error.empty()) return resp;

        // 3xx redirect
        if (resp.status >= 300 && resp.status < 400) {
            auto it = resp.headers.find("location");
            if (it == resp.headers.end()) {
                resp.error = "redirect konum başlığı yok";
                return resp;
            }
            current = it->second;
            continue;
        }
        return resp;
    }

    HttpResponse r;
    r.error = "çok fazla yönlendirme";
    return r;
}

// ── Resolve commit SHA via GitHub API ─────────────────────────────────────────

static std::string resolve_sha(const PkgSpec& spec, bool verbose) {
    // GET https://api.github.com/repos/{user}/{repo}/commits/{ref}
    std::string url = "https://api.github.com/repos/" + spec.user + "/" + spec.repo
                    + "/commits/" + spec.ref;
    if (verbose) std::cout << "  SHA çözümleniyor...\n";

    std::map<std::string, std::string> hdrs;
    hdrs["Accept"]     = "application/vnd.github.sha";
    hdrs["User-Agent"] = "LOOK-Package-Manager/0.25";

    HttpOptions opts;
    opts.timeout_ms = 10000;
    HttpResponse resp = http_request("GET", url, "", hdrs, opts);
    if (!resp.error.empty() || resp.status != 200) return "";

    // Response body is just the 40-char SHA when Accept: application/vnd.github.sha
    std::string sha = resp.body;
    // trim whitespace
    while (!sha.empty() && (sha.back() == '\n' || sha.back() == '\r' || sha.back() == ' '))
        sha.pop_back();
    if (sha.size() == 40) return sha;
    return "";
}

// ── cmd_install ───────────────────────────────────────────────────────────────

int cmd_install(const std::string& pkg, bool verbose) {
    PkgSpec spec;
    try {
        spec = parse_pkg(pkg);
    } catch (const std::exception& e) {
        std::cerr << "Hata: " << e.what() << "\n";
        return 1;
    }

    std::cout << "Yükleniyor: " << spec.user << "/" << spec.repo
              << " (" << spec.ref << ")\n";

    // Download ZIP
    HttpResponse resp = download_follow(spec.zip_url(), verbose);
    if (!resp.error.empty()) {
        std::cerr << "İndirme hatası: " << resp.error << "\n";
        return 1;
    }
    if (resp.status != 200) {
        std::cerr << "GitHub " << resp.status << " döndürdü — paket bulunamadı: "
                  << spec.user << "/" << spec.repo << "\n";
        return 1;
    }

    std::cout << "  " << (resp.body.size() / 1024) << " KB indirildi\n";

    // Extract
    fs::path dest = spec.pkg_dir();
    if (fs::exists(dest)) {
        if (verbose) std::cout << "  Önceki kurulum temizleniyor...\n";
        fs::remove_all(dest);
    }

    std::vector<char> zip_data(resp.body.begin(), resp.body.end());
    if (!extract_zip(zip_data, dest, verbose)) {
        std::cerr << "ZIP çıkartma hatası\n";
        return 1;
    }

    std::cout << "  → " << dest.string() << "\n";

    // Update look.lock
    auto lock_path = fs::current_path() / "look.lock";
    auto lock      = read_lock(lock_path);

    // Try to extract commit SHA from Content-Disposition or URL
    // GitHub sends: attachment; filename=user-repo-{sha}.zip
    std::string sha;
    auto it = resp.headers.find("content-disposition");
    if (it != resp.headers.end()) {
        auto& cd = it->second;
        auto fn_pos = cd.find("filename=");
        if (fn_pos != std::string::npos) {
            std::string fn = cd.substr(fn_pos + 9);
            // strip quotes
            if (!fn.empty() && fn[0] == '"') fn = fn.substr(1);
            auto q = fn.find('"');
            if (q != std::string::npos) fn = fn.substr(0, q);
            // filename = repo-sha.zip → extract sha
            auto dot = fn.rfind(".zip");
            if (dot != std::string::npos) fn = fn.substr(0, dot);
            auto dash = fn.rfind('-');
            if (dash != std::string::npos) {
                sha = fn.substr(dash + 1);
                // GitHub SHAs are 40 hex chars
                if (sha.size() != 40) sha.clear();
            }
        }
    }

    // Try to resolve exact commit SHA if not already extracted from zip filename
    if (sha.empty()) sha = resolve_sha(spec, verbose);

    LockEntry entry;
    entry.ref = spec.ref;
    entry.sha = sha;
    lock[spec.lock_key()] = entry;
    write_lock(lock_path, lock);

    std::cout << "  look.lock güncellendi\n";
    std::cout << "✓ " << spec.lock_key() << " kuruldu\n\n";
    std::cout << "Kullanım:\n";
    std::cout << "  use \"" << spec.pkg_dir() << "/" << spec.repo << ".lk\";\n";

    return 0;
}

// ── cmd_install_all ───────────────────────────────────────────────────────────

int cmd_install_all(bool verbose) {
    auto lock_path = fs::current_path() / "look.lock";
    if (!fs::exists(lock_path)) {
        std::cout << "look.lock bulunamadı — kurulacak paket yok.\n";
        return 0;
    }

    auto lock = read_lock(lock_path);
    if (lock.empty()) {
        std::cout << "look.lock boş — kurulacak paket yok.\n";
        return 0;
    }

    std::cout << lock.size() << " paket yükleniyor...\n";
    int failed = 0;
    for (auto& [key, entry] : lock) {
        std::string pkg_str = "github.com/" + key + "@" + entry.ref;
        if (cmd_install(pkg_str, verbose) != 0) ++failed;
    }

    if (failed > 0) {
        std::cerr << failed << " paket yüklenemedi.\n";
        return 1;
    }
    std::cout << "Tüm paketler yüklendi.\n";
    return 0;
}

} // namespace look
