#!/usr/bin/env bash
# Template render golden test — output must match template_golden.expected BYTE FOR BYTE.
# The expected file was generated by the engine as released in build abb5e2e, i.e. before the
# parsed-template cache and the render rewrite; any difference is a behaviour change.
#   bash tests/template_golden_test.sh ./build/lk            # compare (both engines)
#   bash tests/template_golden_test.sh ./build/lk --update   # regenerate (deliberate changes only)
set -u
LK="${1:-./build/lk}"; MODE="${2:-}"
HERE="$(cd "$(dirname "$0")" && pwd)"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
run() { env "$@" TEMPLATE_DIR="$TMP" LOOK_FILE_ROOT="$TMP" BT_DIR="$TMP" "$LK" "$HERE/template_golden.lk" 2>&1 | grep -v '^\[.*\] \[INFO '; }

if [ "$MODE" = "--update" ]; then
  run > "$HERE/template_golden.expected"
  echo "updated: $(wc -l < "$HERE/template_golden.expected") lines"; exit 0
fi
fail=0
for e in "LOOK_VM_STRICT=1" "LOOK_CLI_VM=0"; do
  run "$e" > "$TMP/got.txt"
  grep -q '^### END$' "$TMP/got.txt" || { echo "  FAIL [$e]: corpus did not run to the end"; tail -3 "$TMP/got.txt" | sed 's/^/    /'; fail=1; continue; }
  if cmp -s "$TMP/got.txt" "$HERE/template_golden.expected"; then
    echo "  OK [$e] byte-identical ($(grep -c '^### ' "$TMP/got.txt") sections)"
  else
    echo "  FAIL [$e]: output differs from the golden file"; diff "$HERE/template_golden.expected" "$TMP/got.txt" | head -12 | sed 's/^/    /'; fail=1
  fi
done
[ $fail -eq 0 ] && echo "PASS: template golden" || { echo "FAIL: template golden"; exit 1; }
