FROM almalinux:8

RUN dnf install -y \
    gcc-toolset-13 \
    gcc-toolset-13-gcc \
    gcc-toolset-13-gcc-c++ \
    cmake \
    make \
    python3 \
    openssl-devel \
    && dnf clean all

# gcc-toolset-13 PATH'e ekle
ENV PATH="/opt/rh/gcc-toolset-13/root/usr/bin:$PATH"
ENV LD_LIBRARY_PATH="/opt/rh/gcc-toolset-13/root/usr/lib64"

WORKDIR /src

CMD ["bash"]
