Listen 8880

<VirtualHost *:8880>
    DocumentRoot /usr/local/psa/admin/htdocs
    DirectoryIndex index.php index.html

    <Directory /usr/local/psa/admin/htdocs>
        AllowOverride All
        Require all granted
        Options +ExecCGI +FollowSymLinks
    </Directory>

    AddType application/x-httpd-php .php
    DirectoryIndex index.php

    ErrorLog /var/log/httpd/plesk-error.log
    CustomLog /var/log/httpd/plesk-access.log combined
</VirtualHost>
